package com.kaelen.restapi;

import java.util.HashMap;
import java.util.Map;

public class CharacterList {
public Map<String, Character> characterMap = new HashMap<>();
    
    
    
    public CharacterList() {
        
        characterMap.put("Admiral", new Character("Admiral", "Bird", "Cranky", 01.27, "aye aye"));
        characterMap.put("Agent S", new Character("Agent S", "Squirrel", "Peppy", 07.02, "sidekick"));
        characterMap.put("Agnes", new Character("Agnes", "Pig", "Sisterly", 04.21, "snuffle"));
        characterMap.put("Al", new Character("Al", "Gorilla", "Lazy", 10.18, "Ayyeeee"));
        characterMap.put("Alfonso", new Character("Alfonso", "Alligator", "Lazy", 06.09, "it'sa me"));
        characterMap.put("Alice", new Character("Alice", "Koala", "Normal", 08.19, "guvnor"));
        characterMap.put("Alli", new Character("Alli", "Alligator", "Snooty", 11.08, "graaagh"));
        characterMap.put("Amelia", new Character("Amelia", "Eagle", "Snooty", 11.19, "cuz"));
        characterMap.put("Anabelle", new Character("Anabelle", "Anteater", "Peppy", 02.16, "snorty"));
        characterMap.put("Anchovy", new Character("Anchovy", "Bird", "Lazy", 03.04, "chuurp"));
        characterMap.put("Ankha", new Character("Ankha", "Cat", "Snooty", 09.22, "me meow"));
        characterMap.put("Angus", new Character("Angus", "Bull", "Cranky", 04.30, "macmoo"));
        characterMap.put("Anicotti", new Character("Anicotti", "Mouse", "Peppy", 02.24, "cannoli"));
        characterMap.put("Annalisa", new Character("Annalisa", "Anteater", "Normal", 02.06, "gumdrop"));
        characterMap.put("Annalise", new Character("Annalise", "Horse", "Snooty", 12.02, "nipper"));
        characterMap.put("Antonio", new Character("Antonio", "Anteater", "Jock", 10.20, "honk"));
        characterMap.put("Apollo", new Character("Apollo", "Eagle", "Cranky", 07.04, "pah"));
        characterMap.put("Apple", new Character("Apple", "Hamster", "Peppy", 09.24, "cheekers"));
        characterMap.put("Astrid", new Character("Astrid", "Kangaroo", "Snooty", 09.08, "my pet"));
        characterMap.put("Audie", new Character("Audie", "Wolf", "Peppy", 08.31, "Foxtrot"));
        characterMap.put("Aurora", new Character("Aurora", "Penguin", "Normal", 01.27, "b-b-baby"));
        characterMap.put("Ava", new Character("Ava", "Chicken", "Normal", 04.28, "beaker"));
        characterMap.put("Avery", new Character("Avery", "Eagle", "Cranky", 02.22, "skree-haw"));
        characterMap.put("Axel", new Character("Axel", "Elephant", "Jock", 03.23, "WHONK"));
        
        characterMap.put("Baabara", new Character("Baabara", "Sheep", "Snooty", 03.28, "daahling"));
        characterMap.put("Bam", new Character("Bam", "Deer", "Jock", 11.07, "kablang"));
        characterMap.put("Bangle", new Character("Bangle", "Tiger", "Peppy", 08.27, "growf"));
        characterMap.put("Barold", new Character("Barold", "Cub", "Lazy", 03.02, "cubby"));
        characterMap.put("Beau", new Character("Beau", "Deer", "Lazy", 04.05, "saltlick"));
        characterMap.put("Bea", new Character("Bea", "Dog", "Normal", 10.15, "bingo"));
        characterMap.put("Beardo", new Character("Beardo", "Bear", "Smug", 09.27, "whiskers"));
        characterMap.put("Becky", new Character("Becky", "Chicken", "Snooty", 12.09, "chicklet"));
        characterMap.put("Bella", new Character("Bella", "Mouse", "Peppy", 12.28, "eeks"));
        characterMap.put("Benedict", new Character("Benedict", "Chicken", "Lazy", 10.10, "uh-hoo"));
        characterMap.put("Benjamin", new Character("Benjamin", "Dog", "Lazy", 08.03, "alrighty"));
        characterMap.put("Bertha", new Character("Bertha", "Hippo", "Normal", 04.25, "bloop"));
        characterMap.put("Bettina", new Character("Bettina", "Mouse", "Normal", 06.12, "eekers"));
        characterMap.put("Bianca", new Character("Bianca", "Tiger", "Peppy", 12.13, "glimmer"));
        characterMap.put("Biff", new Character("Biff", "Hippo", "Jock", 03.29, "squirt"));
        characterMap.put("Big Top", new Character("Big Top", "Elephant", "Lazy", 10.03, "villain"));
        characterMap.put("Bill", new Character("Bill", "Duck", "Jock", 02.01, "quacko"));
        characterMap.put("Billy", new Character("Billy", "Goat", "Jock", 03.25, "dagnaabit"));
        characterMap.put("Biskit", new Character("Biskit", "Dog", "Lazy", 05.13, "dawg"));
        characterMap.put("Bitty", new Character("Bitty", "Hippo", "Snooty", 10.06, "my dear"));
        characterMap.put("Blaire", new Character("Blaire", "Squirrel", "Snooty", 07.03, "nutlet"));
        characterMap.put("Blanche", new Character("Blanche", "Ostrich", "Snooty", 12.21, "quite so"));
        characterMap.put("Bluebear", new Character("Bluebear", "Cub", "Peppy", 06.24, "peach"));
        characterMap.put("Bob", new Character("Bob", "Cat", "Lazy", 01.01, "pthhhpth"));
        characterMap.put("Bonbon", new Character("Bonbon", "Rabbit", "Peppy", 03.03, "deelish"));
        characterMap.put("Bones", new Character("Bones", "Dog", "Lazy", 08.04, "yip yip"));
        characterMap.put("Boomer", new Character("Boomer", "Penguin", "Lazy", 02.07, "human"));
        characterMap.put("Boone", new Character("Boone", "Gorilla", "Jock", 09.12, "baboom"));
        characterMap.put("Boots", new Character("Boots", "Alligator", "Jock", 08.07, "munchie"));
        characterMap.put("Boris", new Character("Boris", "Pig", "Cranky", 11.06, "schnort"));
        characterMap.put("Boyd", new Character("Boyd", "Gorilla", "Cranky", 10.01, "uh-oh"));
        characterMap.put("Bree", new Character("Bree", "Mouse", "Snooty", 07.07, "cheeseball"));
        characterMap.put("Broccolo", new Character("Broccolo", "Mouse", "Lazy", 06.30, "eat it"));
        characterMap.put("Bruce", new Character("Bruce", "Deer", "Cranky", 05.26, "gruff"));
        characterMap.put("Broffina", new Character("Broffina", "Chicken", "Snooty", 10.24, "cluckadoo"));
        characterMap.put("Bubbles", new Character("Bubbles", "Hippo", "Peppy", 09.18, "hipster"));
        characterMap.put("Buck", new Character("Buck", "Horse", "Jock", 04.04, "pardner"));
        characterMap.put("Bud", new Character("Bud", "Lion", "Jock", 08.08, "shredded"));
        characterMap.put("Bunnie", new Character("Bunnie", "Rabbit", "Peppy", 05.09, "tee-hee"));
        characterMap.put("Butch", new Character("Butch", "Dog", "Cranky", 11.01, "ROOOOOWF"));
        characterMap.put("Buzz", new Character("Buzz", "Eagle", "Cranky", 12.07, "captain"));
        
        characterMap.put("Cally", new Character("Cally", "Squirrel", "Normal", 09.04, "WHEE"));
        characterMap.put("Camofrog", new Character("Camofrog", "Frog", "Cranky", 06.05, "ten-hut"));
        characterMap.put("Canberra", new Character("Canberra", "Koala", "Sisterly", 05.14, "nuh uh"));
        characterMap.put("Candi", new Character("Candi", "Mouse", "Peppy", 04.13, "sweetie"));
        characterMap.put("Carmen", new Character("Carmen", "Rabbit", "Peppy", 01.06, "nougat"));
        characterMap.put("Caroline", new Character("Caroline", "Squirrel", "Normal", 07.15, "hulaaaa"));
        characterMap.put("Carrie", new Character("Carrie", "Kangaroo", "Normal", 12.05, "little one"));
        characterMap.put("Cashmere", new Character("Cashmere", "Sheep", "Snooty", 04.02, "baaaby"));
        characterMap.put("Celia", new Character("Celia", "Eagle", "Normal", 03.25, "feathers"));
        characterMap.put("Cesar", new Character("Cesar", "Gorilla", "Cranky", 09.06, "highness"));
        characterMap.put("Chadder", new Character("Chadder", "Mouse", "Smug", 12.15, "fromage"));
        characterMap.put("Charlise", new Character("Charlise", "Bear", "Sisterly", 04.17, "urgh"));
        characterMap.put("Cheri", new Character("Cheri", "Cub", "Peppy", 03.17, "tralala"));
        characterMap.put("Cherry", new Character("Cherry", "Dog", "Sisterly", 05.11, "what what"));
        characterMap.put("Chester", new Character("Chester", "Cub", "Lazy", 08.06, "rookie"));
        characterMap.put("Chevre", new Character("Chevre", "Goat", "Normal", 03.06, "la baa"));
        characterMap.put("Chief", new Character("Chief", "Wolf", "Cranky", 12.19, "harrumph"));
        characterMap.put("Chops", new Character("Chops", "Pig", "Smug", 10.13, "zoink"));
        characterMap.put("Chow", new Character("Chow", "Bear", "Cranky", 07.22, "aiya"));
        characterMap.put("Chrissy", new Character("Chrissy", "Rabbit", "Peppy", 08.28, "sparkles"));
        characterMap.put("Claude", new Character("Claude", "Rabbit", "Lazy", 12.03, "hopalong"));
        characterMap.put("Claudia", new Character("Claudia", "Tiger", "Snooty", 11.22, "ooh la la"));
        characterMap.put("Clay", new Character("Clay", "Hamster", "Lazy", 10.19, "thump"));
        characterMap.put("Cleo", new Character("Cleo", "Horse", "Snooty", 02.09, "sugar"));
        characterMap.put("Clyde", new Character("Clyde", "Horse", "Lazy", 05.01, "clip-clawp"));
        characterMap.put("Coach", new Character("Coach", "Bull", "Jock", 04.29, "stubble"));
        characterMap.put("Cobb", new Character("Cobb", "Pig", "Jock", 10.07, "hot dog"));
        characterMap.put("Coco", new Character("Coco", "Rabbit", "Normal", 03.01, "doyoing"));
        characterMap.put("Cole", new Character("Cole", "Rabbit", "Lazy", 08.10, "duuude"));
        characterMap.put("Colton", new Character("Colton", "Horse", "Smug", 05.22, "check it"));
        characterMap.put("Cookie", new Character("Cookie", "Dog", "Peppy", 06.18, "arfer"));
        characterMap.put("Cousteau", new Character("Cousteau", "Frog", "Jock", 12.17, "oui oui"));
        characterMap.put("Cranston", new Character("Cranston", "Ostrich", "Lazy", 09.23, "sweatband"));
        characterMap.put("Croque", new Character("Croque", "Frog", "Cranky", 07.18, "as if"));
        characterMap.put("Cube", new Character("Cube", "Penguin", "Lazy", 01.29, "brainfreeze"));
        characterMap.put("Curlos", new Character("Curlos", "Sheep", "Smug", 05.08, "shearly"));
        characterMap.put("Curly", new Character("Curly", "Pig", "Jock", 07.26, "nyoink"));
        characterMap.put("Curt", new Character("Curt", "Bear", "Cranky", 07.01, "fuzzball"));
        characterMap.put("Cyd", new Character("Cyd", "Elephant", "Cranky", 06.09, "rockin'"));
        characterMap.put("Cyrano", new Character("Cyrano", "Anteater", "Cranky", 03.09, "ah-CHOO"));
        
        characterMap.put("Daisy", new Character("Daisy", "Dog", "Normal", 11.16, "bow-WOW"));
        characterMap.put("Deena", new Character("Deena", "Duck", "Normal", 06.27, "woowoo"));
        characterMap.put("Deirdre", new Character("Deirdre", "Deer", "Sisterly", 05.04, "whatevs"));
        characterMap.put("Del", new Character("Del", "Alligator", "Cranky", 05.27, "gronk"));
        characterMap.put("Deli", new Character("Deli", "Monkey", "Lazy", 05.24, "monch"));
        characterMap.put("Derwin", new Character("Derwin", "Duck", "Lazy", 05.25, "derrrrr"));
        characterMap.put("Diana", new Character("Diana", "Deer", "Snooty", 01.04, "no doy"));
        characterMap.put("Diva", new Character("Diva", "Frog", "Sisterly", 10.02, "ya know"));
        characterMap.put("Dizzy", new Character("Dizzy", "Elephant", "Lazy", 01.14, "woo-oo"));
        characterMap.put("Dobie", new Character("Dobie", "Wolf", "Cranky", 02.17, "ohmmm"));
        characterMap.put("Doc", new Character("Doc", "Rabbit", "Lazy", 03.16, "ol' bunny"));
        characterMap.put("Dom", new Character("Dom", "Sheep", "Jock", 03.18, "indeedaroo"));
        characterMap.put("Dora", new Character("Dora", "Mouse", "Normal", 02.18, "squeaky"));
        characterMap.put("Dotty", new Character("Dotty", "Rabbit", "Peppy", 03.14, "wee one"));
        characterMap.put("Drago", new Character("Drago", "Alligator", "Lazy", 02.12, "burrrn"));
        characterMap.put("Drake", new Character("Drake", "Duck", "Lazy", 06.25, "quacko"));
        characterMap.put("Drift", new Character("Drift", "Frog", "Jock", 10.09, "brah"));
        
        characterMap.put("Ed", new Character("Ed", "Horse", "Smug", 09.16, "greenhorn"));
        characterMap.put("Egbert", new Character("Egbert", "Chicken", "Lazy", 10.14, "doodle-duh"));
        characterMap.put("Elise", new Character("Elise", "Monkey", "Snooty", 03.21, "puh-lease"));
        characterMap.put("Ellie", new Character("Ellie", "Elephant", "Normal", 05.12, "li'l one"));
        characterMap.put("Elmer", new Character("Elmer", "Horse", "Lazy", 10.05, "tenderfoot"));
        characterMap.put("Eloise", new Character("Eloise", "Elephant", "Snooty", 12.08, "tooooot"));
        characterMap.put("Elvis", new Character("Elvis", "Lion", "Cranky", 07.23, "unh-hunh"));
        characterMap.put("Erik", new Character("Erik", "Deer", "Lazy", 07.27, "chow down"));
        characterMap.put("Eunice", new Character("Eunice", "Sheep", "Normal", 04.03, "lambchop"));
        characterMap.put("Eugene", new Character("Eugene", "Koala", "Smug", 10.26, "yeah buddy"));
        
        characterMap.put("Fang", new Character("Fang", "Wolf", "Cranky", 12.18, "cha-chomp"));
        characterMap.put("Fauna", new Character("Fauna", "Deer", "Normal", 03.26, "dearie"));
        characterMap.put("Felicity", new Character("Felicity", "Cat", "Peppy", 04.30, "mimimi"));
        characterMap.put("Filbert", new Character("Filbert", "Squirrel", "Lazy", 06.03, "bucko"));
        characterMap.put("Flip", new Character("Flip", "Monkey", "Jock", 11.21, "rerack"));
        characterMap.put("Flo", new Character("Flo", "Penguin", "Sisterly", 09.02, "cha"));
        characterMap.put("Flora", new Character("Flora", "Ostrich", "Peppy", 02.09, "pinky"));
        characterMap.put("Flurry", new Character("Flurry", "Hamster", "Normal", 01.30, "powderpuff"));
        characterMap.put("Francine", new Character("Francine", "Rabbit", "Snooty", 01.22, "karat"));
        characterMap.put("Frank", new Character("Frank", "Eagle", "Cranky", 07.30, "crushy"));
        characterMap.put("Freckles", new Character("Freckles", "Duck", "Peppy", 02.19, "ducky"));
        characterMap.put("Freya", new Character("Freya", "Wolf", "Snooty", 12.14, "uff da"));
        characterMap.put("Friga", new Character("Friga", "Penguin", "Snooty", 10.16, "brrmph"));
        characterMap.put("Frita", new Character("Frita", "Sheep", "Sisterly", 07.16, "oh ewe"));
        characterMap.put("Frobert", new Character("Frobert", "Frog", "Jock", 02.08, "fribbit"));
        characterMap.put("Fuchsia", new Character("Fuchsia", "Deer", "Sisterly", 09.19, "precious"));
        
        characterMap.put("Gabi", new Character("Gabi", "Rabbit", "Peppy", 12.16, "honeybun"));
        characterMap.put("Gala", new Character("Gala", "Pig", "Normal", 03.05, "snortie"));
        characterMap.put("Gaston", new Character("Gaston", "Rabbit", "Cranky", 10.28, "mon chou"));
        characterMap.put("Gayle", new Character("Gayle", "Alligator", "Normal", 05.17, "snacky"));
        characterMap.put("Genji", new Character("Genji", "Rabbit", "Jock", 01.21, "mochi"));
        characterMap.put("Gigi", new Character("Gigi", "Frog", "Snooty", 08.11, "ribette"));
        characterMap.put("Gladys", new Character("Gladys", "Ostrich", "Normal", 01.15, "stretch"));
        characterMap.put("Gloria", new Character("Gloria", "Duck", "Snooty", 08.12, "quacker"));
        characterMap.put("Goldie", new Character("Goldie", "Dog", "Normal", 12.27, "woof"));
        characterMap.put("Gonzo", new Character("Gonzo", "Koala", "Cranky", 10.13, "mate"));
        characterMap.put("Goose", new Character("Goose", "Chicken", "Jock", 10.04, "buh-kay"));
        characterMap.put("Graham", new Character("Graham", "Hamster", "Smug", 06.20, "indeed"));
        characterMap.put("Greta", new Character("Greta", "Mouse", "Snooty", 09.05, "yelp"));
        characterMap.put("Grizzly", new Character("Grizzly", "Bear", "Cranky", 07.31, "grrr"));
        characterMap.put("Groucho", new Character("Groucho", "Bear", "Cranky", 10.23, "grumble"));
        characterMap.put("Gruff", new Character("Gruff", "Goat", "Cranky", 08.29, "bleh eh eh"));
        characterMap.put("Gwen", new Character("Gwen", "Penguin", "Snooty", 01.23, "h-h-hon"));
        
        characterMap.put("Hamlet", new Character("Hamlet", "Hamster", "Jock", 05.30, "hammie"));
        characterMap.put("Hamphrey", new Character("Hamphrey", "Hamster", "02.25", 02.25, "snort"));
        characterMap.put("Hans", new Character("Hans", "Gorilla", "Smug", 12.05, "groovy"));
        characterMap.put("Harry", new Character("Harry", "Hippo", "Cranky", 01.07, "beach bum"));
        characterMap.put("Hazel", new Character("Hazel", "Squirrel", "Sisterly", 08.30, "uni-wow"));
        characterMap.put("Henry", new Character("Henry", "Frog", "Smug", 09.21, "snoozit"));
        characterMap.put("Hippeux", new Character("Hippeux", "Hippo", "Smug", 10.15, "natch"));
        characterMap.put("Hopkins", new Character("Hopkins", "Rabbit", "Lazy", 03.11, "thumper"));
        characterMap.put("Hopper", new Character("Hopper", "Penguin", "Cranky", 04.06, "slushie"));
        characterMap.put("Hornsby", new Character("Hornsby", "Rhino", "Lazy", 03.20, "schnozzle"));
        characterMap.put("Huck", new Character("Huck", "Frog", "Lazy", 07.09, "hopper"));
        characterMap.put("Hugh", new Character("Hugh", "Pig", "Lazy", 12.30, "snortle"));
        
        characterMap.put("Iggly", new Character("Iggly", "Penguin", "Jock", 11.02, "waddler"));
        characterMap.put("Ike", new Character("Ike", "Bear", "Cranky", 05.16, "roadie"));
        characterMap.put("Jacob", new Character("Jacob", "Bird", "Lazy", 08.24, "chuuuuurp"));
        characterMap.put("Jacques", new Character("Jacques", "Bird", "Smug", 06.22, "zut alors"));
        characterMap.put("Jambette", new Character("Jambette", "Frog", "Normal", 10.27, "croak-kay"));
        characterMap.put("Jay", new Character("Jay", "Bird", "Jock", 07.17, "heeeeeyy"));
        characterMap.put("Jeremiah", new Character("Jeremiah", "Frog", "Lazy", 07.08, "nee-deep"));
        characterMap.put("Jitters", new Character("Jitters", "Bird", "Jock", 02.02, "bzzert"));
        characterMap.put("Joey", new Character("Joey", "Duck", "Lazy", 01.03, "bleeeeeck"));
        characterMap.put("Judy", new Character("Judy", "Cub", "Snooty", 03.10, "myohmy"));
        characterMap.put("Julia", new Character("Julia", "Ostrich", "Snooty", 07.31, "dahling"));
        characterMap.put("Julian", new Character("Julian", "Horse", "Smug", 03.15, "glitter"));
        characterMap.put("June", new Character("June", "Cub", "Normal", 05.21, "rainbow"));
        characterMap.put("Kabuki", new Character("Kabuki", "Cat", "Cranky", 11.29, "meooo-OH"));
        characterMap.put("Katt", new Character("Katt", "Cat", "Uchi", 04.27, "purrty"));
        characterMap.put("Keaton", new Character("Keaton", "Eagle", "Smug", 06.01, "wingo"));
        characterMap.put("Ken", new Character("Ken", "Chicken", "Smug", 12.23, "no doubt"));
        characterMap.put("Ketchup", new Character("Ketchup", "Duck", "Peppy", 07.27, "bitty"));
        characterMap.put("Kevin", new Character("Kevin", "Pig", "Jock", 04.26, "weeweewee"));
        characterMap.put("Kid Cat", new Character("Kid Cat", "Cat", "Jock", 08.01, "psst"));
        characterMap.put("Kidd", new Character("Kidd", "Goat", "Smug", 06.28, "wut"));
        characterMap.put("Kiki", new Character("Kiki", "Cat", "Normal", 10.08, "kitty cat"));
        characterMap.put("Kitt", new Character("Kitt", "Kangaroo", "Normal", 10.11, "child"));
        characterMap.put("Kitty", new Character("Kitty", "Cat", "Snooty", 02.15, "mrowrr"));
        characterMap.put("Klaus", new Character("Klaus", "Bear", "Smug", 03.31, "strudel"));
        characterMap.put("Knox", new Character("Knox", "Chicken", "Cranky", 11.23, "cluckling"));
        characterMap.put("Kody", new Character("Kody", "Cub", "Jock", 09.28, "grah-grah"));
        characterMap.put("Kyle", new Character("Kyle", "Wolf", "Smug", 12.06, "alpha"));
        
        characterMap.put("Leonardo", new Character("Leonardo", "Tiger", "Jock", 05.15, "flexin"));
        characterMap.put("Leopold", new Character("Leopold", "Lion", "Smug", 08.14, "lion cub"));
        characterMap.put("Lily", new Character("Lily", "Frog", "Normal", 02.04, "toady"));
        characterMap.put("Limberg", new Character("Limberg", "Mouse", "Cranky", 10.17, "squinky"));
        characterMap.put("Lionel", new Character("Lionel", "Lion", "Smug", 07.29, "precisely"));
        characterMap.put("Lobo", new Character("Lobo", "Wolf", "Cranky", 11.05, "ah-rooooo"));
        characterMap.put("Lolly", new Character("Lolly", "Cat", "Normal", 03.27, "bonbon"));
        characterMap.put("Lopez", new Character("Lopez", "Deer", "Smug", 08.20, "buckaroo"));
        characterMap.put("Louie", new Character("Louie", "Gorilla", "Jock", 03.26, "hoo hoo ha"));
        characterMap.put("Lucha", new Character("Lucha", "Bird", "Smug", 12.12, "cacaw"));
        characterMap.put("Lucky", new Character("Lucky", "Dog", "Lazy", 11.04, "rrr-owch"));
        characterMap.put("Lucy", new Character("Lucy", "Pig", "Normal", 06.02, "snoooink"));
        characterMap.put("Lyman", new Character("Lyman", "Koala", "Jock", 10.12, "chips"));
        
        characterMap.put("Mac", new Character("Mac", "Dog", "Jock", 11.11, "woo woof"));
        characterMap.put("Maddie", new Character("Maddie", "Dog", "Peppy", 01.11, "yippee"));
        characterMap.put("Maelle", new Character("Maelle", "Duck", "Snooty", 04.08, "duckling"));
        characterMap.put("Maggie", new Character("Maggie", "Pig", "Normal", 09.03, "schep"));
        characterMap.put("Mallary", new Character("Mallary", "Duck", "Snooty", 11.17, "quackpth"));
        characterMap.put("Maple", new Character("Maple", "Cub", "Normal", 06.15, "honey"));
        characterMap.put("Margie", new Character("Margie", "Elephant", "Normal", 01.28, "tootie"));
        characterMap.put("Marcel", new Character("Marcel", "Dog", "Lazy", 12.31, "non"));
        characterMap.put("Marcie", new Character("Marcie", "Kangaroo", "Normal", 05.31, "pouches"));
        characterMap.put("Marina", new Character("Marina", "Octopus", "Normal", 06.26, "blurp"));
        characterMap.put("Marshal", new Character("Marshal", "Squirrel", "Smug", 09.29, "sulky"));
        characterMap.put("Mathilda", new Character("Mathilda", "Kangaroo", "Snooty", 11.12, "wee baby"));
        characterMap.put("Megan", new Character("Megan", "Bear", "Normal", 03.13, "sundae"));
        characterMap.put("Melba", new Character("Melba", "Koala", "Normal", 04.12, "toasty"));
        characterMap.put("Merengue", new Character("Merengue", "Rhino", "Normal", 03.19, "shortcake"));
        characterMap.put("Merry", new Character("Merry", "Cat", "Peppy", 06.29, "mweee"));
        characterMap.put("Midge", new Character("Midge", "Bird", "Normal", 03.12, "tweedledee"));
        characterMap.put("Mint", new Character("Mint", "Squirrel", "Snooty", 05.02, "ahhhhhh"));
        characterMap.put("Mira", new Character("Mira", "Rabbit", "Sisterly", 07.06, "cottontail"));
        characterMap.put("Miranda", new Character("Miranda", "Duck", "Snooty", 04.23, "quackulous"));
        characterMap.put("Mitzi", new Character("Mitzi", "Cat", "Normal", 09.25, "mew"));
        characterMap.put("Moe", new Character("Moe", "Cat", "Lazy", 01.12, "myawn"));
        characterMap.put("Molly", new Character("Molly", "Duck", "Normal", 03.07, "quackidee"));
        characterMap.put("Monique", new Character("Monique", "Cat", "Snooty", 09.30, "pfffffft"));
        characterMap.put("Monty", new Character("Monty", "Monkey", "Cranky", 12.07, "g'tang"));
        characterMap.put("Moose", new Character("Moose", "Mouse", "Jock", 09.13, "shorty"));
        characterMap.put("Mott", new Character("Mott", "Lion", "Jock", 07.10, "cagey"));
        characterMap.put("Muffy", new Character("Muffy", "Sheep", "Sisterly", 02.14, "nightshade"));
        characterMap.put("Murphy", new Character("Murphy", "Cub", "Cranky", 12.29, "laddie"));
        
        characterMap.put("Nan", new Character("Nan", "Goat", "Normal", 08.24, "kid"));
        characterMap.put("Nana", new Character("Nana", "Monkey", "Normal", 08.23, "po po"));
        characterMap.put("Naomi", new Character("Naomi", "Cow", "Snooty", 02.28, "moolah"));
        characterMap.put("Nate", new Character("Nate", "Bear", "Lazy", 08.16, "yawwwn"));
        characterMap.put("Nibbles", new Character("Nibbles", "Squirrel", "Peppy", 07.19, "niblet"));
        characterMap.put("Norma", new Character("Norma", "Cow", "Normal", 09.20, "hoof hoo"));
        
        characterMap.put("Octavian", new Character("Octavian", "Octopus", "Cranky", 09.20, "sucker"));
        characterMap.put("O'Hare", new Character("O'Hare", "Rabbit", "Smug", 07.24, "amigo"));
        characterMap.put("Olaf", new Character("Olaf", "Anteater", "Smug", 05.19, "whiffa"));
        characterMap.put("Olive", new Character("Olive", "Cub", "Normal", 07.12, "sweet pea"));
        characterMap.put("Olivia", new Character("Olivia", "Cat", "Snooty", 02.03, "purrr"));
        characterMap.put("Opal", new Character("Opal", "Elephant", "Snooty", 01.20, "snoot"));
        characterMap.put("Ozzie", new Character("Ozzie", "Koala", "Lazy", 05.07, "ol' bear"));
        
        characterMap.put("Pancetti", new Character("Pancetti", "Pig", "Snooty", 11.14, "sooey"));
        characterMap.put("Pango", new Character("Pango", "Anteater", "Peppy", 11.09, "snooooof"));
        characterMap.put("Papi", new Character("Papi", "Horse", "Lazy", 01.10, "haaay"));
        characterMap.put("Paolo", new Character("Paolo", "Elephant", "Lazy", 05.05, "pal"));
        characterMap.put("Pashmina", new Character("Pashmina", "Goat", "Sisterly", 12.26, "kidders"));
        characterMap.put("Pate", new Character("Pate", "Duck", "Peppy", 02.23, "quackle"));
        characterMap.put("Patty", new Character("Patty", "Cow", "Peppy", 05.10, "how-now"));
        characterMap.put("Paula", new Character("Paula", "Bear", "Sisterly", 03.22, "yodelay"));
        characterMap.put("Peaches", new Character("Peaches", "Horse", "Normal", 11.28, "neighbor"));
        characterMap.put("Peanut", new Character("Peanut", "Squirrel", "Peppy", 06.08, "slacker"));
        characterMap.put("Pecan", new Character("Pecan", "Squirrel", "Snooty", 09.10, "chipmunk"));
        characterMap.put("Peck", new Character("Peck", "Bird", "Jock", 07.25, "crunch"));
        characterMap.put("Peewee", new Character("Peewee", "Gorilla", "Cranky", 09.11, "li'l dude"));
        characterMap.put("Peggy", new Character("Peggy", "Pig", "Peppy", 05.23, "shweetie"));
        characterMap.put("Pekoe", new Character("Pekoe", "Cub", "Normal", 05.18, "bud"));
        characterMap.put("Penelope", new Character("Penelope", "Mouse", "Peppy", 02.05, "oh bow"));
        characterMap.put("Phil", new Character("Phil", "Ostrich", "Smug", 11.21, "hurk"));
        characterMap.put("Phoebe", new Character("Phoebe", "Ostrich", "Sisterly", 04.22, "sparky"));
        characterMap.put("Pierce", new Character("Pierce", "Eagle", "Jock", 01.08, "hawkeye"));
        characterMap.put("Pietro", new Character("Pietro", "Sheep", "Smug", 04.19, "honk honk"));
        characterMap.put("Pinky", new Character("Pinky", "Bear", "Peppy", 09.09, "wah"));
        characterMap.put("Piper", new Character("Piper", "Bird", "Peppy", 04.18, "chickadee"));
        characterMap.put("Peppy", new Character("Peppy", "Rabbit", "Peppy", 06.14, "li'l hare"));
        characterMap.put("Plucky", new Character("Plucky", "Chicken", "Sisterly", 10.12, "chicky-poo"));
        characterMap.put("Pompom", new Character("Pompom", "Duck", "Peppy", 02.11, "rah rah"));
        characterMap.put("Poncho", new Character("Poncho", "Cub", "Jock", 01.02, "li'l bear"));
        characterMap.put("Poppy", new Character("Poppy", "Squirrel", "Normal", 08.05, "nutty"));
        characterMap.put("Portia", new Character("Portia", "Dog", "Snooty", 10.25, "ruffian"));
        characterMap.put("Prince", new Character("Prince", "Frog", "Lazy", 07.21, "burrup"));
        characterMap.put("Puck", new Character("Puck", "Penguin", "Lazy", 02.21, "brrrrrrrrr"));
        characterMap.put("Puddles", new Character("Puddles", "Frog", "Peppy", 01.13, "splish"));
        characterMap.put("Pudge", new Character("Pudge", "Cub", "Lazy", 06.11, "pudgy"));
        characterMap.put("Punchy", new Character("Punchy", "Cat", "Lazy", 04.11, "mrmpht"));
        characterMap.put("Purrl", new Character("Purrl", "Cat", "Snooty", 05.29, "kitten"));
        
        characterMap.put("Queenie", new Character("Queenie", "Ostrich", "Snooty", 11.13, "chicken"));
        characterMap.put("Quilson", new Character("Quilson", "Duck", "Smug", 12.22, "ridukulous"));
        
        characterMap.put("Raddle", new Character("Raddle", "Frog", "Lazy", 06.06, "aaach-"));
        characterMap.put("Rasher", new Character("Rasher", "Pig", "Cranky", 04.07, "swine"));
        characterMap.put("Raymond", new Character("Raymond", "Cat", "Smug", 10.01, "crisp"));
        characterMap.put("Renee", new Character("Renee", "Rhino", "Sisterly", 05.28, "yo yo yo"));
        characterMap.put("Reneigh", new Character("Reneigh", "Horse", "Sisterly", 06.04, "ayup, yup"));
        characterMap.put("Rex", new Character("Rex", "Lion", "Lazy", 07.24, "cool cat"));
        characterMap.put("Rhonda", new Character("Rhonda", "Rhino", "Normal", 01.24, "bigfoot"));
        characterMap.put("Ribbot", new Character("Ribbot", "Frog", "Jock", 02.13, "zzrrbbitt"));
        characterMap.put("Ricky", new Character("Ricky", "Squirrel", "Cranky", 09.14, "nutcase"));
        characterMap.put("Rizzo", new Character("Rizzo", "Mouse", "Cranky", 01.17, "squee"));
        characterMap.put("Roald", new Character("Roald", "Penguin", "Jock", 01.05, "b-b-buddy"));
        characterMap.put("Robin", new Character("Robin", "Bird", "Snooty", 12.04, "la-di-da"));
        characterMap.put("Rocco", new Character("Rocco", "Hippo", "Cranky", 08.18, "hippie"));
        characterMap.put("Rocket", new Character("Rocket", "Gorilla", "Sisterly", 04.14, "vroom"));
        characterMap.put("Rod", new Character("Rod", "Mouse", "Jock", 08.14, "ace"));
        characterMap.put("Rodeo", new Character("Rodeo", "Bull", "Lazy", 10.29, "chaps"));
        characterMap.put("Rodney", new Character("Rodney", "Hamster", "Smug", 11.10, "le ham"));
        characterMap.put("Rolf", new Character("Rolf", "Tiger", "Cranky", 08.22, "grrrolf"));
        characterMap.put("Rooney", new Character("Rooney", "Kangaroo", "Cranky", 12.01, "punches"));
        characterMap.put("Rory", new Character("Rory", "Lion", "Jock", 08.07, "capital"));
        characterMap.put("Roscoe", new Character("Roscoe", "Horse", "Cranky", 06.16, "nay"));
        characterMap.put("Rosie", new Character("Rosie", "Cat", "Peppy", 02.27, "silly"));
        characterMap.put("Rowan", new Character("Rowan", "Tiger", "Jock", 08.26, "mango"));
        characterMap.put("Ruby", new Character("Ruby", "Rabbit", "Peppy", 12.25, "li'l ears"));
        characterMap.put("Rudy", new Character("Rudy", "Cat", "Jock", 12.20, "mush"));
        
        characterMap.put("Sally", new Character("Sally", "Squirrel", "Normal", 06.19, "nutmeg"));
        characterMap.put("Samson", new Character("Samson", "Mouse", "Jock", 07.05, "pipsqueak"));
        characterMap.put("Sandy", new Character("Sandy", "Ostrich", "Normal", 10.21, "speedy"));
        characterMap.put("Savannah", new Character("Savannah", "Horse", "Normal", 01.25, "y'all"));
        characterMap.put("Scoot", new Character("Scoot", "Duck", "Jock", 06.13, "zip zoom"));
        characterMap.put("Shari", new Character("Shari", "Monkey", "Sisterly", 04.10, "cheeky"));
        characterMap.put("Sheldon", new Character("Sheldon", "Squirrel", "Jock", 02.26, "cardio"));
        characterMap.put("Shep", new Character("Shep", "Dog", "Smug", 11.24, "baa baa baa"));
        characterMap.put("Sherb", new Character("Sherb", "Goat", "Lazy", 01.18, "bawwww"));
        characterMap.put("Simon", new Character("Simon", "Monkey", "Lazy", 01.19, "zzzook"));
        characterMap.put("Skye", new Character("Skye", "Wolf", "Normal", 03.24, "airmail"));
        characterMap.put("Sly", new Character("Sly", "Alligator", "Jock", 11.15, "hoo-rah"));
        characterMap.put("Snake", new Character("Snake", "Rabbit", "Jock", 11.03, "bunyip"));
        characterMap.put("Snooty", new Character("Snooty", "Anteater", "Snooty", 10.24, "Snifffff"));
        characterMap.put("Soleil", new Character("Soleil", "Hamster", "Snooty", 08.09, "tarnation"));
        characterMap.put("Sparro", new Character("Sparro", "Bird", "Jock", 11.20, "like whoa"));
        characterMap.put("Spike", new Character("Spike", "Rhino", "Cranky", 06.17, "punk"));
        characterMap.put("Spork", new Character("Spork", "Pig", "Lazy", 09.03, "snork"));
        characterMap.put("Sprinkle", new Character("Sprinkle", "Penguin", "Peppy", 02.20, "frappe"));
        characterMap.put("Sprocket", new Character("Sprocket", "Ostrich", "Jock", 12.01, "zort"));
        characterMap.put("Static", new Character("Static", "Squirrel", "Cranky", 07.09, "krzzt"));
        characterMap.put("Stella", new Character("Stella", "Sheep", "Normal", 04.09, "baa-dabing"));
        characterMap.put("Sterling", new Character("Sterling", "Eagle", "Jock", 12.11, "skraaaaw"));
        characterMap.put("Stinky", new Character("Stinky", "Cat", "Jock", 08.17, "GAHHHH"));
        characterMap.put("Stitches", new Character("Stitches", "Cub", "Lazy", 02.10, "stuffin'"));
        characterMap.put("Stu", new Character("Stu", "Bull", "Lazy", 04.20, "moo-dude"));
        characterMap.put("Sydney", new Character("Sydney", "Koala", "Normal", 06.21, "sunshine"));
        characterMap.put("Sylvana", new Character("Sylvana", "Squirrel", "Normal", 10.22, "hubbub"));
        characterMap.put("Sylvia", new Character("Sylvia", "Kanagroo", "Sisterly", 05.03, "boing"));
        
        characterMap.put("Tabby", new Character("Tabby", "Cat", "Peppy", 08.13, "me-WOW"));
        characterMap.put("Tad", new Character("Tad", "Frog", "Jock", 08.03, "sluuuurp"));
        characterMap.put("Tammi", new Character("Tammi", "Monkey", "Peppy", 04.02, "chimpy"));
        characterMap.put("Tammy", new Character("Tammy", "Cub", "Uchi", 06.23, "ya heard"));
        characterMap.put("Tangy", new Character("Tangy", "Cat", "Peppy", 06.17, "reeeeeOWR"));
        characterMap.put("Tank", new Character("Tank", "Rhino", "JOck", 05.06, "kerPOW"));
        characterMap.put("T-Bone", new Character("T-Bone", "Bull", "Cranky", 05.20, "moocher"));
        characterMap.put("Tasha", new Character("Tasha", "Squirrel", "Snooty", 11.30, "nice nice"));
        characterMap.put("Teddy", new Character("Teddy", "Bear", "Jock", 09.26, "grooof"));
        characterMap.put("Tex", new Character("Tex", "Penguin", "Smug", 10.06, "picante"));
        characterMap.put("Tia", new Character("Tia", "Elephant", "Normal", 11.18, "teacup"));
        characterMap.put("Tiffany", new Character("Tiffany", "Rabbit", "Snooty", 01.09, "bun bun"));
        characterMap.put("Timbra", new Character("Timbra", "Sheep", "Snooty", 10.21, "pine nut"));
        characterMap.put("Tipper", new Character("Tipper", "Cow", "Snooty", 08.25, "pushy"));
        characterMap.put("Tom", new Character("Tom", "Cat", "Cranky", 12.10, "me-YOWZA"));
        characterMap.put("Truffles", new Character("Truffles", "Pig", "Peppy", 07.28, "snoutie"));
        characterMap.put("Tucker", new Character("Tucker", "Elephant", "Lazy", 09.07, "fuzzers"));
        characterMap.put("Tutu", new Character("Tutu", "Bear", "Peppy", 09.15, "twinkles"));
        characterMap.put("Twiggy", new Character("Twiggy", "Bird", "Peppy", 07.13, "cheepers"));
        characterMap.put("Tybalt", new Character("Tybalt", "Tiger", "Jock", 08.19, "grrRAH"));
        
        characterMap.put("Ursala", new Character("Ursala", "Bear", "Sisterly", 0116, "grooomph"));
        
        characterMap.put("Velma", new Character("Velma", "Goat", "Snooty", 01.14, "blih"));
        characterMap.put("Vesta", new Character("Vesta", "Sheep", "Normal", 04.16, "baaaffo"));
        characterMap.put("Vic", new Character("Vic", "Bull", "Cranky", 12.29, "cud"));
        characterMap.put("Victoria", new Character("Victoria", "Horse", "Peppy", 07.11, "sugar cube"));
        characterMap.put("Violet", new Character("Violet", "Gorilla", "Snooty", 09.01, "sweetie"));
        characterMap.put("Vivian", new Character("Vivian", "Wolf", "Snooty", 01.26, "piffle"));
        characterMap.put("Vladimir", new Character("Vladimir", "Cub", "Cranky", 08.02, "nyet"));
        
        characterMap.put("Wade", new Character("Wade", "Penguin", "Lazy", 10.30, "so it goes"));
        characterMap.put("Walker", new Character("Walker", "Dog", "Lazy", 06.10, "wuh"));
        characterMap.put("Walt", new Character("Walt", "Kanagroo", "Cranky", 04.24, "pockets"));
        characterMap.put("Wart Jr.", new Character("Wart Jr.", "Frog", "Cranky", 08.21, "grr-ribbit"));
        characterMap.put("Weber", new Character("Weber", "Duck", "Lazy", 06.30, "quaa"));
        characterMap.put("Wendy", new Character("Wendy", "Sheep", "Peppy", 08.15, "lambkins"));
        characterMap.put("Winnie", new Character("Winnie", "Horse", "Peppy", 01.31, "hay-OK"));
        characterMap.put("Whitney", new Character("Whitney", "Wolf", "Snooty", 09.17, "snappy"));
        characterMap.put("Willow", new Character("Willow", "Sheep", "Snooty", 11.26, "bo peep"));
        characterMap.put("Wolfgang", new Character("Wolfgang", "Wolf", "Cranky", 11.25, "snarrrl"));
        
        characterMap.put("Yuka", new Character("Yuka", "Koala", "Snooty", 07.20, "tsk tsk"));
        
        characterMap.put("Zell", new Character("Zell", "Deer", "Smug", 06.07, "pronk"));
        characterMap.put("Zucker", new Character("Zucker", "Octopus", "Lazy", 03.08, "bloop"));

    }
    
    public Character getCharacter(String name) {
        return characterMap.get(name);
    }
    
    public void putCharacter(Character character) {
        characterMap.put(character.getName(), character);
    }
}